#!/usr/bin/env node
/**
 * Setup Config Script
 *
 * Copies the appropriate configuration files to public/config/ based on
 * the APP_CONFIG environment variable.
 *
 * Usage:
 *   APP_CONFIG=royal-ambassadors node scripts/setup-config.js
 *   APP_CONFIG=home-chores node scripts/setup-config.js
 *
 * Default: royal-ambassadors
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync, readdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

// Get config name from environment or default to royal-ambassadors
const configName = process.env.APP_CONFIG || 'royal-ambassadors';
const configDir = join(rootDir, 'configs', configName);
const publicConfigDir = join(rootDir, 'public', 'config');
const publicDataDir = join(rootDir, 'public', 'data');

console.log(`Setting up configuration: ${configName}`);

// Validate config exists
if (!existsSync(configDir)) {
  console.error(`Error: Configuration directory not found: ${configDir}`);
  console.error(`Available configs: ${readdirSync(join(rootDir, 'configs')).join(', ')}`);
  process.exit(1);
}

// Create public/config directory
mkdirSync(publicConfigDir, { recursive: true });

// Copy app.config.json and theme.config.json
const appConfigSrc = join(configDir, 'app.config.json');
const themeConfigSrc = join(configDir, 'theme.config.json');

if (!existsSync(appConfigSrc)) {
  console.error(`Error: app.config.json not found in ${configDir}`);
  process.exit(1);
}

if (!existsSync(themeConfigSrc)) {
  console.error(`Error: theme.config.json not found in ${configDir}`);
  process.exit(1);
}

copyFileSync(appConfigSrc, join(publicConfigDir, 'app.config.json'));
copyFileSync(themeConfigSrc, join(publicConfigDir, 'theme.config.json'));
console.log('  Copied app.config.json and theme.config.json');

// Copy data files (leaderboard.json, rules.json, games.json) if they exist
const dataDir = join(configDir, 'data');
if (existsSync(dataDir)) {
  mkdirSync(publicDataDir, { recursive: true });

  const dataFiles = ['leaderboard.json', 'rules.json', 'games.json'];
  dataFiles.forEach(file => {
    const src = join(dataDir, file);
    if (existsSync(src)) {
      copyFileSync(src, join(publicDataDir, file));
      console.log(`  Copied data/${file}`);
    }
  });
}

// Read app config to determine basePath for vite
const appConfig = JSON.parse(readFileSync(appConfigSrc, 'utf-8'));

// Write a .env.local file with the basePath for vite to pick up
// This allows vite.config.ts to use the correct basePath
// Using .env.local because it's loaded by Vite and has higher priority
const envContent = `# Auto-generated by setup-config.js
VITE_APP_CONFIG=${configName}
VITE_BASE_PATH=${appConfig.basePath}
`;
writeFileSync(join(rootDir, '.env.local'), envContent);
console.log(`  Generated .env.local with basePath: ${appConfig.basePath}`);

console.log(`Configuration setup complete for: ${configName}`);
